spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
# # jdnc data information
#  sql:
#    init:
#      schema-locations: classpath*:db/h2/schema.sql
#      data-locations: classpath*:db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
# # sql pretty print
#    properties:
#      hibernate:
#        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT}
            client-secret: ${GITHUB_SECRET}
            scope:
              - user
              - user:email
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    auth: true
    starttls:
      enable: true
server:
  servlet:
    encoding:
      force-response: true
#  ssl:
#    key-store: classpath:localhost.p12  # 인증서 경로
#    key-store-type: PKCS12  # 인증서 형식
#    key-store-password: changeit  # 인증서 비밀번호
    # 여기서 비밀번호인 changeit은 비밀번호를 설정하지 않았을 때의 기본값입니다.
    # 인증서 비밀번호는 인증서를 생성할 때 설정하거나 생성 후 변경해줄 수 있습니다.
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 1440
