spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
# # sql pretty print
#    properties:
#      hibernate:
#        format_sql: true
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG
#  sql:
#    init:
#      schema-locations: classpath*:db/h2/schema.sql
#      data-locations: classpath*:db/h2/data.sql
