INSERT INTO MEMBER (EMAIL, NAME, PHONE, MEMBER_STATUS) VALUES ('roki@hello.com', 'roki', '010-1111-1111', 'MEMBER_ACTIVE');
INSERT INTO MEMBER (EMAIL, NAME, PHONE, MEMBER_STATUS) VALUES ('toki@hello.com', 'toki', '010-2222-2222', 'MEMBER_ACTIVE');
INSERT INTO MEMBER (EMAIL, NAME, PHONE, MEMBER_STATUS) VALUES ('poki@hello.com', 'poki', '010-3333-3333', 'MEMBER_ACTIVE');

INSERT INTO STAMP (STAMP_COUNT, MEMBER_ID) VALUES (0, 1);
INSERT INTO STAMP (STAMP_COUNT, MEMBER_ID) VALUES (0, 2);
INSERT INTO STAMP (STAMP_COUNT, MEMBER_ID) VALUES (0, 3);


INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('아메리카노', 'Americano', 4000, 'AME', 'COFFEE_FOR_SALE');
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('카페 라테', 'Caffe Late', 4500, 'CFL', 'COFFEE_FOR_SALE');
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('카라멜 라떼', 'Caramel Latte', 4500, 'CRL', 'COFFEE_FOR_SALE');
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('바닐라 라떼', 'Vanilla Latte', 5000, 'VNL', 'COFFEE_FOR_SALE');
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('자바칩 프라푸치노', 'Java chip Frappuccino', 6500, 'JCF', 'COFFEE_FOR_SALE');