INSERT INTO MEMBER (EMAIL, PHONE, MEMBER_STATUS, FIRST_NAME, MIDDLE_OPTION, LAST_NAME, PASSWORD) VALUES ('roki@hello.com', '010-1111-1111', 'MEMBER_ACTIVE', 'roki', 'middle', 'yoon', '{bcrypt}$2a$10$V776q8TelhVGK4U0Ry7BxOhCnr17iLwM8DkWNPbjnRig0XZ5gakMK');
INSERT INTO MEMBER (EMAIL, PHONE, MEMBER_STATUS, FIRST_NAME, MIDDLE_OPTION, LAST_NAME, PASSWORD) VALUES ('toki@hello.com', '010-2222-2222', 'MEMBER_ACTIVE', 'toki', 'middle', 'yoon', '{bcrypt}$2a$10$1GMYhLZuSPi6UtrnL9RDrOE2ZE/x6KlLH7gh9iCuIAFNSQjDlsxEi');
INSERT INTO MEMBER (EMAIL, PHONE, MEMBER_STATUS, FIRST_NAME, MIDDLE_OPTION, LAST_NAME, PASSWORD) VALUES ('poki@hello.com', '010-3333-3333', 'MEMBER_ACTIVE', 'poki', 'middle', 'yoon', '{bcrypt}$2a$10$TNAGo3SmXTmI5LDLa/iO2uyzQLRMUGF1C7R1mJT2jug2fVvsvHl2m');

INSERT INTO STAMP (STAMP_COUNT, MEMBER_ID) VALUES (0, 1);
INSERT INTO STAMP (STAMP_COUNT, MEMBER_ID) VALUES (0, 2);
INSERT INTO STAMP (STAMP_COUNT, MEMBER_ID) VALUES (0, 3);

INSERT INTO MEMBER_ROLES (MEMBER_MEMBER_ID, ROLES) VALUES (1, 'ADMIN');
INSERT INTO MEMBER_ROLES (MEMBER_MEMBER_ID, ROLES) VALUES (1, 'USER');
INSERT INTO MEMBER_ROLES (MEMBER_MEMBER_ID, ROLES) VALUES (2, 'ADMIN');
INSERT INTO MEMBER_ROLES (MEMBER_MEMBER_ID, ROLES) VALUES (3, 'USER');

INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('아메리카노', 'Americano', 4000, 'AME', 'COFFEE_FOR_SALE');
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('카페 라테', 'Caffe Late', 4500, 'CFL', 'COFFEE_FOR_SALE');
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('카라멜 라떼', 'Caramel Latte', 4500, 'CRL', 'COFFEE_FOR_SALE');
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('바닐라 라떼', 'Vanilla Latte', 5000, 'VNL', 'COFFEE_FOR_SALE');
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS) VALUES ('자바칩 프라푸치노', 'Java chip Frappuccino', 6500, 'JCF', 'COFFEE_FOR_SALE');