INSERT INTO MEMBER (EMAIL, NAME, PHONE, CREATED_AT, MEMBER_STATUS, LAST_MODIFIED_AT) VALUES ('roki@hello.com', 'roki', '010-1234-5678', now(), 'MEMBER_ACTIVE', now());
INSERT INTO MEMBER (EMAIL, NAME, PHONE, CREATED_AT, MEMBER_STATUS, LAST_MODIFIED_AT) VALUES ('toki@hello.com', 'toki', '010-1111-2222', now(), 'MEMBER_ACTIVE', now());
INSERT INTO MEMBER (EMAIL, NAME, PHONE, CREATED_AT, MEMBER_STATUS, LAST_MODIFIED_AT) VALUES ('poki@hello.com', 'poki', '010-9999-8888', now(), 'MEMBER_ACTIVE', now());

INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS, CREATED_AT, LAST_MODIFIED_AT) VALUES ('아메리카노', 'Americano', 4000, 'AME', 'COFFEE_FOR_SALE', now(), now());
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS, CREATED_AT, LAST_MODIFIED_AT) VALUES ('카페 라테', 'Caffe Late', 4500, 'CFL', 'COFFEE_FOR_SALE', now(), now());
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS, CREATED_AT, LAST_MODIFIED_AT) VALUES ('카라멜 라떼', 'Caramel Latte', 4500, 'CRL', 'COFFEE_FOR_SALE', now(), now());
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS, CREATED_AT, LAST_MODIFIED_AT) VALUES ('바닐라 라떼', 'Vanilla Latte', 5000, 'VNL', 'COFFEE_FOR_SALE', now(), now());
INSERT INTO COFFEE (KOR_NAME, ENG_NAME, PRICE, COFFEE_CODE, COFFEE_STATUS, CREATED_AT, LAST_MODIFIED_AT) VALUES ('자바칩 프라푸치노', 'Java chip Frappuccino', 6500, 'JCF', 'COFFEE_FOR_SALE', now(), now());